export TEXMFHOME=/home/kanezaki/tex/docs/texmf:$TEXMFHOME
export BIBINPUTS=/home/kanezaki/tex/docs/bibliography:$BIBINPUTS

SRC = vosch_poster

all:
	pdflatex $(SRC).tex

clean:
	rm -f *.aux *.blg *.log *.lof *.log *.lot *.out *.toc *~ *.dvi *.ps *.pdf




















